#!/bin/sh
#https://github.com/abdulhamitmercan
# Dışarıdan gelen APN, kullanıcı adı ve şifreyi al, eğer verilmeyen bir parametre varsa varsayılan değer kullan
APN="${1:-internet}"
USERNAME="${2:-default_user}"   # Varsayılan kullanıcı adı https://github.com/abdulhamitmercan
PASSWORD="${3:-default_pass}"   # Varsayılan şifre bdlhmrcn

while true; do
    # Ping ile bağlantıyı kontrol et
    ping -I wwan0 -c 1 -s 0 8.8.8.8

    # Eğer bağlantı başarılıysa
    if [ $? -eq 0 ]; then
        echo "Connection up, reconnect not required..."
    else
        echo "Connection down, reconnecting..."

        # Modemi online moda geçir
        mode=$(sudo qmicli -d /dev/cdc-wdm0 --dms-get-operating-mode)
        if [[ "$mode" != *"online"* ]]; then
            echo "Modem is offline . connections..."
            sudo qmicli -d /dev/cdc-wdm0 --dms-set-operating-mode='online'
        else
            echo "modem is in online mode ."
        fi

        # WWAN0 interface
        echo "configuring WWAN0 interfays ..."
        sudo ip link set wwan0 down
        echo 'Y' | sudo tee /sys/class/net/wwan0/qmi/raw_ip
        sudo ip link set wwan0 up

        # Veri formatt
        echo "checking datas format ..."
        sudo qmicli -d /dev/cdc-wdm0 --wda-get-data-format

        # Mobil connection
        echo "starting mobiles connection ..."
        sudo qmicli -p -d /dev/cdc-wdm0 --device-open-net='net-raw-ip|net-no-qos-header' --wds-start-network="apn='$APN',username='$USERNAME',password='$PASSWORD',ip-type=4" --client-no-release-cid

        # IP adresss
        echo "IP adresses and default routes are being made ..."
        sudo udhcpc -q -f -i wwan0

        # Durum kontrolü ve hizmeti başlatma
        echo "checking connection..."
        sudo systemctl status qmi_reconnect.service
        if ! sudo systemctl is-active --quiet qmi_reconnect.service; then
            echo "qmi_reconnect services stopprd  restarting ..."
            sudo systemctl start qmi_reconnect.service
        else
            echo "qmi_reconnect service running."
        fi
    fi

    # 10 saniye bekle
    sleep 10
done

